### ISSUE TITLE
bu-pdf-dir and ways to specify path

### ISSUE THREAD

**Issue by vkazanov** [plantarum/bibtex-utils#4]
On Linux generally there are two ways to specify a path:

1. `(setq bu-pdf-dir "~/Documents/bibtex/pdfs")`
2. `(setq bu-pdf-dir "~/Documents/bibtex/pdfs/")`

Because the `bu-open-doc` function just concats path components to check for pdfs in the directory this may result in a broken path: `"~/Documents/bibtex/pdfsmykey.pdf"`.

To avoid this it's generally better to use something like: `(concat (file-name-as-directory bu-pdf-dir) (cdr (assoc "=key=" ) ".pdf")`. Notice the usage of `file-name-as-directory`.

I could come up with a patch but the change is trivial :-)

**Comment by plantarum** [comment]
Done, thanks!
